# Generated by Django 5.2.17 on 2026-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head', 'Head'), ('legal_officer', 'Legal Officer')], default='admin', max_length=20),
        ),
    ]
