# Generated by Django 5.2.17 on 2026-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head', 'Head'), ('legal_officer', 'Legal Officer'), ('reporter', 'Reporter')], default='admin', max_length=20),
        ),
    ]
