# Generated by Django 5.2.17 on 2026-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='Last time a notification was sent for this deadline', null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='Last time a notification was sent for this hearing', null=True),
        ),
    ]
