# Generated by Django 5.2.17 on 2026-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='source',
            field=models.CharField(choices=[('initial_submission', 'Initial Submission'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
    ]
