# Generated by Django 5.2.17 on 2026-08-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('core', '0002_auto_20260816_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.campus'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='campus',
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.casecategory'),
        ),
        migrations.AlterField(
            model_name='case',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.department'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='CaseCategory',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
