# Generated by Django 5.2.17 on 2026-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_rejection_reason_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('registered', 'Registered'), ('active', 'Active'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
