# Generated by Django 5.2.17 on 2026-08-16 11:19

from django.db import migrations


def seed_campuses(apps, schema_editor):
    """
    Data migration to seed the five known campuses from project spec.
    Campuses: Tedrose, Facile, Tseda, Maraki, GC
    """
    Campus = apps.get_model('core', 'Campus')
    
    campuses = [
        {'name': 'Tedrose', 'code': 'TED'},
        {'name': 'Facile', 'code': 'FAC'},
        {'name': 'Tseda', 'code': 'TSE'},
        {'name': 'Maraki', 'code': 'MAR'},
        {'name': 'GC', 'code': 'GC'},
    ]
    
    for campus_data in campuses:
        Campus.objects.create(**campus_data)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_campuses, migrations.RunPython.noop),
    ]
