# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations


def seed_reference_data(apps, schema_editor):
    """
    Data migration to seed real University of Gondar reference data.
    Updates existing data to match actual campuses, departments, and case categories.
    """
    Campus = apps.get_model('core', 'Campus')
    Department = apps.get_model('core', 'Department')
    CaseCategory = apps.get_model('core', 'CaseCategory')
    
    # Update existing campuses to correct spelling
    campus_updates = {
        'TED': 'Tewodros (Main) Campus',
        'FAC': 'Fasilo Campus',
        'TSE': 'Tseda Campus',
        'MAR': 'Maraki Campus',
        'GC': 'Atse Tewodros Campus'  # Renaming GC to Atse Tewodros
    }
    
    for code, name in campus_updates.items():
        Campus.objects.filter(code=code).update(name=name)
    
    # GC is now Atse Tewodros, so we don't need to create a separate ATW campus
    # Just ensure we have the 5 campuses with correct names
    
    # Delete and recreate departments (no foreign key dependencies)
    Department.objects.all().delete()
    
    # Get campus objects for department creation
    campus_objects = {c.code: c for c in Campus.objects.all()}
    
    # Seed Departments tied to appropriate campuses
    departments = [
        # Tewodros (Main) Campus - Central administration and key departments
        {'name': 'Law', 'code': 'LAW', 'campus': campus_objects.get('TED')},
        {'name': 'Business & Economics', 'code': 'BEC', 'campus': campus_objects.get('TED')},
        {'name': 'Social Sciences', 'code': 'SSC', 'campus': campus_objects.get('TED')},
        
        # Fasilo Campus - Engineering and Technology
        {'name': 'Engineering', 'code': 'ENG', 'campus': campus_objects.get('FAC')},
        {'name': 'Computer Science', 'code': 'CS', 'campus': campus_objects.get('FAC')},
        
        # Atse Tewodros Campus (GC code) - Health Sciences
        {'name': 'Medicine', 'code': 'MED', 'campus': campus_objects.get('GC')},
        
        # Maraki Campus - Agriculture and Natural Resources
        {'name': 'Agriculture', 'code': 'AGR', 'campus': campus_objects.get('MAR')},
        
        # Tseda Campus - Additional departments (use different name to avoid unique constraint)
        {'name': 'Social Sciences & Humanities', 'code': 'SSC2', 'campus': campus_objects.get('TSE')},
    ]
    
    for dept_data in departments:
        if dept_data['campus']:  # Only create if campus exists
            Department.objects.get_or_create(
                code=dept_data['code'],
                defaults={
                    'name': dept_data['name'],
                    'campus': dept_data['campus']
                }
            )
    
    # Update existing case categories (preserve to avoid foreign key issues)
    category_updates = {
        'scholarship': ('Scholarship', 'Scholarship agreements, sponsor coordination, and student support documentation'),
        'disciplaine': ('Disciplinary', 'Student and staff disciplinary cases, hearings, and resolutions'),
        'Property': ('Property', 'University property disputes, infrastructure legal matters, and facility use cases')
    }
    
    for old_name, (new_name, description) in category_updates.items():
        CaseCategory.objects.filter(name=old_name).update(
            name=new_name,
            description=description
        )
    
    # Add missing categories using get_or_create to avoid duplicates
    missing_categories = [
        {
            'name': 'Personal',
            'description': 'Individual legal concerns, personal grievances, and confidential matters'
        },
        {
            'name': 'Institutional',
            'description': 'University-wide institutional legal matters, policy issues, and administrative cases'
        },
    ]
    
    for category_data in missing_categories:
        CaseCategory.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260816_1419'),
    ]

    operations = [
        migrations.RunPython(seed_reference_data, migrations.RunPython.noop),
    ]
